version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=contact-list
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql