version: "3"

services:

  database:
    image: postgres:12.3
    container_name: booking_service_db
    environment:
      POSTGRES_PASSWORD: booking-service
    ports:
      - 5432:5432

  booking:
    image: openjdk:21
    container_name: booking_service
    links:
      - database
    volumes:
      - ../build/libs/booking-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8085:8080
    command: /usr/java/openjdk-21/bin/java -jar /app/app.jar
    depends_on:
      - database
