spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8081
app:
  kafka:
    kafkaOrderTopic: "order-topic"
    kafkaOrderStatusServiceTopic: "order-status-service-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
