spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: book-service
  data:
    redis:
      host: localhost
      port: 6379
app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cache-names:
      - books
      - book
    caches:
      books:
        expire: 100s
      book:
        expire: 100s