version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=news-service
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql